@php
    /** @var \App\Domain\Catalog\Entities\Project $project */
    /** @var array<string, mixed> $metadata */
    /** @var string $generatedAt */

    $blueprint = (array) ($metadata['blueprint'] ?? []);
    $design = (array) ($metadata['design'] ?? []);
    $brief = (array) ($metadata['brief'] ?? []);
    $github = (array) ($metadata['github'] ?? []);
    $content = (array) ($metadata['content'] ?? []);
    $deployment = (array) ($metadata['deployment'] ?? []);

    $primaryLocale = $project->locale->value;
    $targetLocales = (array) ($metadata['target_locales'] ?? []);
    $producedLocales = (array) ($content['produced_locales'] ?? []);
    $allLocales = array_values(array_unique(array_merge([$primaryLocale], array_map('strval', $targetLocales), array_map('strval', $producedLocales))));

    $pageCount = (int) ($content['pages_count'] ?? count((array) ($content['page_ids'] ?? [])));
    $articleCount = (int) ($content['articles_count'] ?? count((array) ($content['article_ids'] ?? [])));
    $faqCount = (int) ($content['faqs_count'] ?? count((array) ($content['faq_ids'] ?? [])));

    $blueprintPages = (array) ($blueprint['pages'] ?? []);
    $tokens = (array) ($design['tokens'] ?? []);
@endphp
# CLAUDE.md — {{ $project->name }}

> Per-platform context generated by WebFactory on {{ $generatedAt }}. Read this first.

## What this is

**{{ $project->name }}** is a production web platform generated by [WebFactory](https://github.com/webfactory-org/webfactory-app) from a single idea. It is a Laravel + Filament application — same stack as the WebFactory factory itself, so conventions transfer.

@if (! empty($project->description))
**Original idea**: {{ $project->description }}
@endif

## Stack (inherited from WebFactory)

- **Backend**: PHP 8.3 · Laravel 13 · Filament v4 · Livewire 3 · Horizon · Sanctum
- **Frontend**: Blade templates (public surface). Tailwind v4 via Vite.
- **Data**: PostgreSQL 16 + pgvector · Redis 7 ×2 (cache + sessions) · Meilisearch · S3-compatible storage
- **Tests**: Pest 4 + ArchTest · Vitest · Playwright
- **Quality**: Pint · PHPStan level 8 · ESLint · Prettier

## Project identity

| Key | Value |
|---|---|
| Slug | `{{ $project->slug->value }}` |
| Status | `{{ $project->status->value }}` |
| Primary locale | `{{ $primaryLocale }}` |
| Target locales | {{ empty($targetLocales) ? '_(none — primary only)_' : '`'.implode('`, `', $targetLocales).'`' }} |
| Primary domain | {{ $project->primaryDomain ?: '_(not set)_' }} |
| Owner ID | `{{ $project->ownerId }}` |
| Virality score | {{ $project->viralityScore }} / 100 |
| Value score | {{ $project->valueScore }} / 100 |

## Live deployment

@if (! empty($deployment))
| Key | Value |
|---|---|
| Provider | `{{ $deployment['provider'] ?? 'unknown' }}` |
| Live URL | {{ ! empty($deployment['live_url']) ? '<'.$deployment['live_url'].'>' : '_(none)_' }} |
| Preview URL | {{ ! empty($deployment['preview_url']) ? '<'.$deployment['preview_url'].'>' : '_(none)_' }} |
| Deployment ID | `{{ $deployment['deployment_id'] ?? 'n/a' }}` |
| Success | {{ ! empty($deployment['success']) ? 'yes' : 'no' }} |
@else
_Not yet deployed at the time this file was generated._
@endif

## GitHub repository

@if (! empty($github))
| Key | Value |
|---|---|
| Full name | `{{ $github['full_name'] ?? 'n/a' }}` |
| HTML URL | {{ ! empty($github['html_url']) ? '<'.$github['html_url'].'>' : '_(n/a)_' }} |
| SSH URL | `{{ $github['ssh_url'] ?? 'n/a' }}` |
| Default branch | `{{ $github['default_branch'] ?? 'main' }}` |
@else
_Repository not yet provisioned at the time this file was generated._
@endif

## Content footprint

- **{{ $pageCount }}** pages · **{{ $articleCount }}** articles · **{{ $faqCount }}** FAQs
- Locales actually produced: {{ empty($producedLocales) ? '_(pending)_' : '`'.implode('`, `', $producedLocales).'`' }}
- Across all locales: {{ count($allLocales) }} variant(s)

## Blueprint pages (canonical structure)

@if (! empty($blueprintPages))
@foreach ($blueprintPages as $page)
- `{{ $page['slug'] ?? '(no-slug)' }}` — {{ $page['title'] ?? '(no-title)' }} · _type_: `{{ $page['type'] ?? 'static' }}`
@endforeach
@else
_No blueprint pages declared._
@endif

## Design tokens (excerpt)

@if (! empty($tokens))
@foreach (array_slice($tokens, 0, 12, true) as $key => $value)
- `{{ $key }}` = `{{ is_scalar($value) ? $value : json_encode($value) }}`
@endforeach
@if (count($tokens) > 12)
- _… and {{ count($tokens) - 12 }} more (see `metadata.design.tokens` in the project record)._
@endif
@else
_No design tokens persisted._
@endif

## Brief footprint (Sprint 6)

@if (! empty($brief))
- File count: **{{ $brief['file_count'] ?? 'n/a' }}**
- Checksum (SHA-256): `{{ $brief['checksum'] ?? 'n/a' }}`
@else
_No brief persisted._
@endif

## Conventions (inherited)

- `declare(strict_types=1);` everywhere; classes `final` by default.
- DDD layout under `app/` — `Domain` is pure (no Illuminate/Symfony/Filament/Infrastructure imports). Enforced by `tests/Arch/ArchitectureTest.php`.
- DI bindings centralized in `app/Providers/DomainServiceProvider.php`.
- All async work goes through Horizon queues.
- Conventional Commits required (commitlint enforced).

## How to run locally

```bash
cp .env.example .env          # set ADMIN_EMAIL / ADMIN_PASSWORD
make setup                    # build + up + composer + npm + key + migrate + seed + build
# http://localhost/up   → 200
# http://localhost/admin → Filament login
```

## Need to regenerate this file?

It is rebuilt by WebFactory's `WriteProjectDocumentationJob` whenever the source pipeline re-runs `ContentProduced`. Manual edits will be **overwritten** on the next pipeline pass — keep your customizations in a separate `CLAUDE.local.md`.

---

_Generated by WebFactory `ProjectDocumentationGenerator` on {{ $generatedAt }}._
