<?php

declare(strict_types=1);

namespace App\Infrastructure\Pipeline;

use App\Application\Catalog\DTOs\ContentBundle;
use App\Application\Catalog\Services\ContentProductionService;
use App\Domain\Catalog\Entities\Project;
use App\Models\Article;
use App\Models\Faq;
use App\Models\Page;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

/**
 * Sprint-15 placeholder for pipeline step 6 — multilingual content production.
 *
 * Strategy:
 *   - Read the blueprint stored in `project.metadata.blueprint`
 *   - For each locale: produce a Page per blueprint page entry, a pillar
 *     Article per journey, and a fixed set of 3 FAQ entries
 *   - All rows are persisted in the multi-tenant Content tables (Sprint 7)
 *
 * Sprint 19 will swap this for a real Claude-backed adapter that uses the KB
 * (Sprint 7), AudienceContext (Sprint 9), and the AEO + JSON-LD primitives
 * (Sprint 8) to generate authentic locale-aware content.
 */
final class HeuristicContentProductionService implements ContentProductionService
{
    public function produce(Project $project, array $locales): ContentBundle
    {
        $projectIdInt = (int) $project->id;

        /** @var array<string, mixed> $blueprint */
        $blueprint = (array) ($project->metadata['blueprint'] ?? []);
        /** @var list<array{slug: string, title: string, type: string}> $bpPages */
        $bpPages = (array) ($blueprint['pages'] ?? []);
        /** @var list<array{name: string, steps: list<string>}> $bpJourneys */
        $bpJourneys = (array) ($blueprint['journeys'] ?? []);

        $pageIds = [];
        $articleIds = [];
        $faqIds = [];
        $producedLocales = [];

        DB::transaction(function () use (
            $projectIdInt, $project, $locales, $bpPages, $bpJourneys,
            &$pageIds, &$articleIds, &$faqIds, &$producedLocales,
        ): void {
            foreach ($locales as $locale) {
                $producedLocales[] = $locale;

                // Always create at least a home page even with empty blueprint
                if ($bpPages === []) {
                    $bpPages = [['slug' => 'home', 'title' => $project->name, 'type' => 'landing']];
                }

                foreach ($bpPages as $bp) {
                    /** @var Page $page */
                    $page = Page::query()->updateOrCreate(
                        ['project_id' => $projectIdInt, 'slug' => $bp['slug'], 'locale' => $locale],
                        [
                            'title' => $bp['title'],
                            'type' => $bp['type'] ?? 'standard',
                            'status' => 'published',
                            'published_at' => now(),
                            'content_blocks' => [
                                ['type' => 'hero', 'title' => $bp['title']],
                                ['type' => 'aeo_answer', 'question' => 'What is '.$bp['title'].'?', 'answer' => 'Auto-generated by WebFactory pipeline step 6.'],
                            ],
                            'meta_tags' => ['locale' => $locale],
                        ],
                    );
                    $pageIds[] = (int) $page->getKey();
                }

                foreach ($bpJourneys as $journey) {
                    $title = (string) ($journey['name'] ?? 'Pillar article');
                    $body = "## {$title}\n\nMulti-step journey covering: ".implode(', ', (array) ($journey['steps'] ?? [])).'.';

                    /** @var Article $article */
                    $article = Article::query()->updateOrCreate(
                        ['project_id' => $projectIdInt, 'slug' => Str::slug($title.'-'.$locale), 'locale' => $locale],
                        [
                            'title' => $title,
                            'excerpt' => Str::limit($body, 160),
                            'body' => $body,
                            'is_pillar' => true,
                            'status' => 'published',
                            'published_at' => now(),
                            'word_count' => str_word_count($body),
                            'reading_time_minutes' => max(1, (int) ceil(str_word_count($body) / 200)),
                            'quality_score' => 80,
                            'seo_keywords' => array_map('strtolower', explode(' ', $title)),
                        ],
                    );
                    $articleIds[] = (int) $article->getKey();
                }

                foreach ($this->seedFaqs($project, $locale) as [$question, $answer, $category]) {
                    /** @var Faq $faq */
                    $faq = Faq::query()->updateOrCreate(
                        ['project_id' => $projectIdInt, 'locale' => $locale, 'question' => $question],
                        [
                            'answer' => $answer,
                            'category' => $category,
                            'status' => 'published',
                            'is_featured' => false,
                        ],
                    );
                    $faqIds[] = (int) $faq->getKey();
                }
            }
        });

        return new ContentBundle(
            pageIds: array_values(array_unique($pageIds)),
            articleIds: array_values(array_unique($articleIds)),
            faqIds: array_values(array_unique($faqIds)),
            producedLocales: array_values(array_unique($producedLocales)),
        );
    }

    /**
     * @return list<array{0: string, 1: string, 2: string}>
     */
    private function seedFaqs(Project $project, string $locale): array
    {
        return [
            ['What is '.$project->name.'?', $project->name.' is a platform built with WebFactory.', 'general'],
            ['Is the service available worldwide?', 'Yes — multilingual delivery covers all supported locales.', 'general'],
            ['How do I get support?', 'Use the contact form or the in-app help widget.', 'support'],
        ];
    }
}
